# This workflow will run CI tests on the Essential Feed project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Essential Feed CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test-macos:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode version
        run: sudo xcode-select -switch /Applications/Xcode_15.3.app

      - name: Xcode version
        run: /usr/bin/xcodebuild -version

      - name: Build and test for macOS
        run: xcodebuild clean build test -project EssentialFeed.xcodeproj -scheme "CI_macOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

  build-and-test-ios:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode version
        run: sudo xcode-select -switch /Applications/Xcode_15.3.app

      - name: Xcode version
        run: /usr/bin/xcodebuild -version
      
      - name: Build and Test
        run: xcodebuild clean build test -project EssentialFeed.xcodeproj -scheme "CI_iOS" -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.4' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO